### ISSUE TITLE
How to add ripples programatically ?

### ISSUE THREAD

**Issue by Madebym** [sirxemic/jquery.ripples#11]
I've tried this, but it doesn't work.

    $('#add').on('click', function(e){
    e.preventDefault();
    $('#test').ripples("drop", 200, 200, 20, 0.04);
    })

**Comment by Madebym** [comment]
Also, is it possible to create only one ripple? Preferably without the mouseover, but rather from code.

That way it won't be too much processor intensive, leaving open some nice possibilities for loading/splash-screen animations.

**Comment by sirxemic** [comment]
You're reporting a bug and making a suggestion.

Concerning your code not working - unfortunately I'd need a bit more context to address it - it should work, but maybe you've got something else not set-up correctly. Maybe your selector(s) is/are wrong? Can you perhaps create a small test case I can try out, showing that it indeed does not work correctly?

Concerning your suggestion to disable mouseover ripples - it could be a good idea for an extension, I guess. Though it wouldn't make it significantly less intensive for the processor, as you might think. The performance gain would be negligible.

**Comment by sirxemic** [comment]
Concerning that suggestion - I just added the "interactive" property/option. (a034a0f318b4e46f24cb238600e8fbc56ba8a527)
