### ISSUE TITLE
re-initiate after destroy

### ISSUE THREAD

**Issue by fraserYT** [sirxemic/jquery.ripples#12]
Love the effect, thanks so much for your stellar work. I know that if I hide the effect, I can use "$('body, main').ripples('show');" to show it again, but how would I start the effect again once it's been destroyed, other than forcing a reload of the page?

**Comment by sirxemic** [comment]
Re-initiating should be as simple as initiating it. That is, just calling `.ripples({ <options> })`.

**Comment by fraserYT** [comment]
I thought it should be that simple, but it's not working for me, so must be something with my own code that's preventing it. I'll keep at it. Thanks

**Comment by sirxemic** [comment]
Maybe there is some edge-case I have overlooked. Maybe something in combination with styling, and certain options perhaps... If you figure out it is a very specific case instead of a bug in your own code, please report back.

**Comment by fraserYT** [comment]
I had been using an older version. When I updated to the latest, this now works, so I can confirm it was definitely no issue with the plugin. As an aside, I can confirm that destroying, changing the background of the page, then re-initiating, is a successful workaround for issue #5.
