### ISSUE TITLE
Set the website of this GitHub repo to the demo

### ISSUE THREAD

**Issue by dandv** [sirxemic/jquery.ripples#13]
http://sirxemic.github.io/jquery.ripples/

Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by sirxemic** [comment]
Thanks for the suggestion!
