### ISSUE TITLE
How to change the circle ripple into ellipse ripple

### ISSUE THREAD

**Issue by Sylvanassssss** [sirxemic/jquery.ripples#15]
Hey, I'am working on a program that mainly focus on how to use some animation effect to display the rhythm of a music. The effect is shown below.
![qq 20150801144827](https://cloud.githubusercontent.com/assets/13597720/9020940/7a40e5e8-385c-11e5-9694-2bdf048a145c.png)
The ellipse will diffuse like the ripple. I want to add your effect to my project, but I'm a beginner on programming and just knowing a few things about javascript, html5 and d3.js (nothing about webgl).
Can you tell me how to change the shape of the ripple?

You can also contact me by sending a email to suyue0731@gmail.com.
Thank you very much!

**Comment by sirxemic** [comment]
You can change the lines at https://github.com/sirxemic/jquery.ripples/blob/master/js/jquery.ripples.js#L410-L415 to:

```javascript
'float ratio = 2.0;', // tweak this to your tastes
'float average = (',
  'ratio * texture2D(texture, coord - dx).r +',
  'texture2D(texture, coord - dy).r +',
  'ratio * texture2D(texture, coord + dx).r +',
  'texture2D(texture, coord + dy).r',
') / (2.0 * ratio + 2.0);',
```

**Comment by Sylvanassssss** [comment]
Thank you very much for your help!

I like this effect very much !

 

发件人: Pim Schreurs [mailto:notifications@github.com] 
发送时间: 2015年8月1日 19:21
收件人: sirxemic/jquery.ripples
抄送: Sylvanassssss
主题: Re: [jquery.ripples] How to change the circle ripple into ellipse ripple (#15)

 

You can change the lines at https://github.com/sirxemic/jquery.ripples/blob/master/js/jquery.ripples.js#L410-L415 to:

'float ratio = 2.0;', // tweak this to your tastes
'float average = (',
  'ratio * texture2D(texture, coord - dx).r +',
  'texture2D(texture, coord - dy).r +',
  'ratio * texture2D(texture, coord + dx).r +',
  'texture2D(texture, coord + dy).r',
') / (2.0 * ratio + 2.0);',

**Comment by kshepherd2005** [comment]
Still works in 2017.
