### ISSUE TITLE
Is there a way to remove the shader

### ISSUE THREAD

**Issue by piskello** [sirxemic/jquery.ripples#18]
Hello, I'm trying to remove teh whiate shade: I would use it on a black text and preserve only the distortion, without the shade.

**Comment by sirxemic** [comment]
https://github.com/sirxemic/jquery.ripples/blob/master/js/jquery.ripples.js#L478-L479

The "specular" variable adds the white shade you are talking about. Removing it from those two lines should do the trick.

**Comment by piskello** [comment]
Thank you :+1: !
