### ISSUE TITLE
adding tags for the repo

### ISSUE THREAD

**Issue by Amomo** [sirxemic/jquery.ripples#22]
Hello @sirxemic ,

I am a member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library on CDN.
Could you please adding git tags for this repo?

Git tag can help us to know your release version.
And, we could auto-update the lib by a new tag.

Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8216

**Comment by sirxemic** [comment]
I created a tag as you requested. Do I also have to create a `package.json` file or something? How will the system otherwise know which file to host?

**Comment by Amomo** [comment]
It will be great if you could add a `package.json` and point out which files should we host in a "main" field in package.json!

We add a new library by manual process, at the same time, we will add lines of [auto-update config](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md) in `package.json`, so an auto-update script will check for new release hourly.

Thanks for your help again!

**Comment by Amomo** [comment]
jquery.ripples is on cdnjs now. 😄 
https://cdnjs.com/libraries/jquery.ripples
