### ISSUE TITLE
Undefined var

### ISSUE THREAD

**Issue by roizpi** [sirxemic/jquery.ripples#24]
What is may causing this error? your <a href="http://sirxemic.github.io/jquery.ripples/">web example</a> works on my browser with jQuery 2.0.0, but with my project it causes the following errors:

Console log with jQuery 3.1.0:

```
jQuery.Deferred exception: gl is undefined
Ripples.prototype.drop@file:///..../scripts/lib/jquery.ripples.js:566:7
$.fn.ripples/<@file:///..../scripts/lib/jquery.ripples.js:652:9
.each@https://code.jquery.com/jquery-3.1.0.min.js:2:2813
r.prototype.each@https://code.jquery.com/jquery-3.1.0.min.js:2:1001
$.fn.ripples@file:///..../scripts/lib/jquery.ripples.js:640:12
enableRipples@file:///..../scripts/main.js:125:3
@file:///..../scripts/main.js:15:3
g/</j@https://code.jquery.com/jquery-3.1.0.min.js:2:29566
g/</k<@https://code.jquery.com/jquery-3.1.0.min.js:2:29882
undefined
--------------------------------------
  TypeError: gl is undefined	 jquery.ripples.js (line 566, col 7)
  gl.viewport(0, 0, this.resolution, this.resolution);

```

Console log with jQuery 2.0.0:
```
  TypeError: gl is undefined	 jquery.ripples.js (line 566, col 7)
  gl.viewport(0, 0, this.resolution, this.resolution);
```

**Comment by sirxemic** [comment]
Does the element you initialize the plugin on have a background image set? When an element does not have a valid background image (see line 93), it will just not initialize the plugin. If you then call the `drop` method, it will throw that error.

I guess I should make it more robust and make it possible to change the background image later without resetting the plugin.

**Comment by roizpi** [comment]
Actually I was applying the ripples to the father of the image's container. I didn't analyze the source code yet, so I didn't read the 97th line commentary. Although the guide is easy to understand, I'd suggest to add this info to the Readme.md.

It works fine now.

Thank you for your prompt answer.
