### ISSUE TITLE
ripples doesn't work with background-attachment: fixed

### ISSUE THREAD

**Issue by neorganic** [sirxemic/jquery.ripples#25]
So basically that's the problem. Maybe you can fix this or have a work around this? It seems that  it's  a bug. It's trying to .getClientBoundRects() from window when it usually gets it from body, the actual thing that's being rippled.

**Comment by sirxemic** [comment]
Can you give me minimal test case? I can't reproduce it. In what browsers is it happening?

**Comment by neorganic** [comment]
After you said you can't reproduce it - I had and idea on what's going on. I just tested it with https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js - it works! Earlier i was trying with  jQuery v3.1.0 (compressed version)  . If you still need a link with examples of these two jqueries - I can post them here.

**Comment by sirxemic** [comment]
It should work for jQuery 3 as well now. Thanks for the bug report!
