### ISSUE TITLE
webGL on mobile

### ISSUE THREAD

**Issue by peterlunglum** [sirxemic/jquery.ripples#28]
Is there a reason why this effect doesn't work on mobile? Looking at webGL support, and it looks like chrome on phones should be able to render the effect, but for some reason it isn't.

**Comment by sirxemic** [comment]
The effect uses the `OES_texture_float` WebGL extension and also renders to floating point textures. Unfortunately not all mobile devices support these features.

I've tested it on some iOS devices and it runs fine on those. Maybe you can elaborate a bit? Which devices did you expect it to work on?

**Comment by sirxemic** [comment]
@peterlunglum Unless you can elaborate, I'm closing this issue.
