### ISSUE TITLE
on windows resize event

### ISSUE THREAD

**Issue by AminulBD** [sirxemic/jquery.ripples#31]
Ripples not working great when the window is resized. I think reinitialize needed on window resize.

What do you think?

**Comment by sirxemic** [comment]
You'll need to be a little bit more specific. The canvas is resized to its parent when the window is resized, or is supposed to, at least. Could you show me the HTML and the CSS you are using for the element you are applying the effect on?

**Comment by AminulBD** [comment]
Oh, Later I get that it's working fine on window resize event. But, If the element has transition property then this will not work great.

Here you can get live example: https://codepen.io/aminul/full/WjxoyK/

Resize window (Height) then you will see what's is going there.

**Comment by sirxemic** [comment]
The issue in that example isn't the window resize, it's that the canvas element doesn't resize when its parent's CSS is updated.

Here is an example how you can fix it with a workaround:
https://codepen.io/anon/pen/Vbjrjz

**Comment by AminulBD** [comment]
Owao! Simple. But, I didn't understand this simple thing before. 💯
