### ISSUE TITLE
Console Error in Chrome

### ISSUE THREAD

**Issue by Rubel-hossain** [sirxemic/jquery.ripples#34]
showing console error in chrome browser :-
"Access to Image at 'file:///E:/Themeix/HTML5/SPA%20Beauty%20Care%20Html%20Template/preview/images/header-bg.jpg' from origin 'null' has been blocked by CORS policy: Invalid response. Origin 'null' is therefore not allowed access."

**Comment by sirxemic** [comment]
See http://www.chrome-allow-file-access-from-file.com/ .
