### ISSUE TITLE
can't use in body with cover style

### ISSUE THREAD

**Issue by teneous** [sirxemic/jquery.ripples#35]
when body use background picture with url and use style=background-size:cover;
the image disapper, if I give it a width and height and It works. 

how to solve this problem.thanks in advance

**Comment by sirxemic** [comment]
I need a bit more details. Could you maybe show me an example?

**Comment by lpender** [comment]
The image adjusts to fill the vertical width of the window (within limits), but doesn't make any effort to keep the image centered when you adjust the horizontal width of the window.

landscape ratio:

(looks ok)

![image](https://user-images.githubusercontent.com/1406554/32343879-69ab90e4-bfdb-11e7-9eea-0b5db39bd7fe.png)

portrait ratio:

(only see the red rose on the left--the yellow rose on the right is cut off)

![image](https://user-images.githubusercontent.com/1406554/32343946-9407b994-bfdb-11e7-9a1b-26f2fb5a1228.png)

**Comment by lpender** [comment]
Nevermind, this was solved by using `background-position: center` !
