### ISSUE TITLE
Interactive

### ISSUE THREAD

**Issue by NWray** [sirxemic/jquery.ripples#36]
Is there a way to use a particular layer to be the receptor for interactions (mouse move and click), but have the effect be on a different layer? I ask because I want the ripples to be behind other objects, but it appears that you have to make the top most div be the one with the effects if you want interactivity.

**Comment by sirxemic** [comment]
You can listen to mouse events on a certain element and call `$(selector).ripples('drop', x, y, radius, strength)` manually. You'd need to experiment a bit with the values for `x`, `y`, `radius` and `strength`, though.

Something along the lines of:

```js
var $interactiveElement = ...
var $rippleElement = ...
$interactiveElement.on('mousemove', function(e) {
  var x = e.pageX - $rippleElement.offset().left, 
      y = e.pageY - $rippleElement.offset().top
  $rippleElement.ripples('drop', x, y, 20, 0.05)
})
```
