### ISSUE TITLE
Interactive

### ISSUE THREAD

**Issue by Karine91** [sirxemic/jquery.ripples#38]
Hello, I am set parameter interactive false, but ripple still work on mousemove...(sorry for my bad English)

**Comment by sirxemic** [comment]
You really need to give me more information in order to help you. Like, what is your code like, and what do you see happening?

**Comment by Karine91** [comment]
I want run automatic drops, whithout dops on a mousemove. my code:
try {
        $('.gallery-shark').ripples({
            resolution: 512,
            dropRadius: 20, //px
            perturbance: 0.01,
            interactive: false
        });
    }
    catch (e) {
        $('.error').show().text(e);
    }

    // Automatic drops
    setInterval(function() {
        var $el = $('.gallery-shark');
        var x = Math.random() * $el.outerWidth();
        var y = Math.random() * $el.outerHeight();
        var dropRadius = 20;
        var strength = 0.01 + Math.random() * 0.01;
        $el.ripples('drop', x, y, dropRadius, strength);
    }, 2000);

**Comment by Karine91** [comment]
And now drops appear on a some distance from cursor

**Comment by sirxemic** [comment]
Can you make a minimal working example showcasing the bug? Because that code is fine, it almost seems like something outside of that code is the root cause...

**Comment by Karine91** [comment]
You can see whole project there https://github.com/Karine91/oceanarium

**Comment by sirxemic** [comment]
Ah, that explains a lot: you're using a very old version :)
