### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by else05** [sirxemic/jquery.ripples#4]
![capture](https://cloud.githubusercontent.com/assets/10355875/5852807/6eb00574-a257-11e4-81a7-2383891bd3ad.PNG)

**Comment by sirxemic** [comment]
Nice find. Could you tell me what you get for `$(<element the effect is applied on>).css("background-position")` ?

Is this happening for the demo or something your own?
