### ISSUE TITLE
with background-image set, image is being requested twice

### ISSUE THREAD

**Issue by js-d-coder** [sirxemic/jquery.ripples#43]
I am setting ripples effect on body and setting background-image on the same using in CSS file.  
But I am observing that the image is being requested twice in network tab of chrome devtools. First time it is requested by html document via css (of course) and second one is being requested by ripples.js.  
I don't think this is a good thing, requesting same file twice at same time could slow the webpage loading, right?  
Should I be concerned about it? Can you please do something about it, to fix the problem?  
btw, thanks a lot for this library, extremely useful :-)

**Comment by sirxemic** [comment]
I'm afraid I can't do anything about that. If you set up your caching settings properly, and if the images are small (as they should be :wink: ) it shouldn't be an issue, though.

If you really want to prevent this behaviour though, you could load the effect on an element without a background image and use the `imageUrl` property instead. This way it will only do 1 request. Note that this has the disadvantage that there will be no background image until javascript is loaded.

**Comment by js-d-coder** [comment]
That is what I did... thanks.
