### ISSUE TITLE
IPad: can not run in ipad safari

### ISSUE THREAD

**Issue by hycript** [sirxemic/jquery.ripples#45]
environment: ipad mini , ipad air
version: 10.3.3

**Comment by sirxemic** [comment]
So you're saying that on those devices you're getting an error message in the bottom-left corner when running the demo (https://sirxemic.github.io/jquery.ripples/) ?

Unfortunately I don't have an iPad Mini or an iPad Air to test with. Unless you're *not* getting that error, it doesn't seem like something that can be fixed.

**Comment by sirxemic** [comment]
Could you tell me if you're getting that error on the demo page or not? I can't really help any further unless I have more information.

**Comment by wm370857724** [comment]
This plugin use some webgl2.0 api like bindBuffer,safari in iOS don't support until now.
