### ISSUE TITLE
Problem in WordPress version

### ISSUE THREAD

**Issue by irsruhul** [sirxemic/jquery.ripples#46]
Hi, this is a nice plugin. I have used it in html version. There is no problem. But, when I trying to integrate in wordpress theme, it showing following errors in console

> Uncaught TypeError: (intermediate value)(intermediate value) is not a function
    

> Uncaught TypeError: $(...).ripples is not a function

Please can you help me by fixing this.
Thanks

**Comment by sirxemic** [comment]
This looks like a wordpress issue and has nothing to do with this plugin... like, it seems you forgot to include jQuery, this plugin, or both in the right way. Maybe I can help, but since this is not an issue with the plugin itself I'm just gonna close this.

**Comment by kowsar89** [comment]
To whom it may concern, this fork fixed compatibility issues with WordPress
https://github.com/kowsar89/jquery.ripples
