### ISSUE TITLE
How to properly use it with jQuery.noConflict?

### ISSUE THREAD

**Issue by mavstuff** [sirxemic/jquery.ripples#48]
Thanks for the nice plugin! I need to use the with jQuery.noConflict. How ca I do this?

**Comment by sirxemic** [comment]
I have no idea. I never used jQuery.noConflict before and the `noConflict` code I added is just a pattern I copied over from other jQuery plugins. 

Try the jQuery documentation, Google or StackOverflow.

**Comment by mavstuff** [comment]
I have just replaced code 	
$ = $ && $.hasOwnProperty('default') ? $['default'] : $;
with 
$ = jQuery;

Also the code to install ripples:
jQuery('.homebanr').ripples({
		resolution: 500,
		perturbance: 0.01
});

have a nice day!
