### ISSUE TITLE
Chrome Ripple Effect

### ISSUE THREAD

**Issue by Shraddha2702** [sirxemic/jquery.ripples#49]
Internet Explorer and Firefox display really amazing Ripple Effects
But the same code doesn't create that kind of effect in Chrome.
Any idea, why that's happening?

**Comment by floweri19** [comment]
I have the same thing. I found out that if you go to Chrome settings (Advanced -> System) and change "Use hardware acceleration when available" to ON, then it works smoothly like in Firefox.  (Probably because webGL etc use GPU, so they need that extra power to work better). 

Cheers <3

**Comment by Shraddha2702** [comment]
Let me try this one.. Thank you :)

**Comment by mohitgithub3443** [comment]
The same exact problem of Water Ripple Effect I'm facing while coding. It works fine in Firefox But There is an issue in chrome. @Shraddha2702 Have you got any solution?
All others can reply too.
