### ISSUE TITLE
IN Internet Explorer Browser, Ripple effect is not working.

### ISSUE THREAD

**Issue by raj-barnwal** [sirxemic/jquery.ripples#50]

**Comment by sirxemic** [comment]
Last time I checked it did work, so I need a bit more information. What's the OS and IE version?

**Comment by raj-barnwal** [comment]
IE 11 and Windows 8.1 OS

**Comment by sirxemic** [comment]
Which version of IE exactly? Is it the latest version? An update might help. See https://github.com/sirxemic/jquery.ripples/issues/2#issuecomment-92789980

If you don't know how to check which version it is, see https://support.microsoft.com/help/17295/windows-internet-explorer-which-version

If it is the latest version, please report what you see in the console (press F12, I believe). Also, when you run the demo at https://sirxemic.github.io/jquery.ripples/, does an error message appear in the bottom-left corner?
