### ISSUE TITLE
Newbie help

### ISSUE THREAD

**Issue by interiors3d** [sirxemic/jquery.ripples#53]
@sirxemic 
Awesome effect! I'd like to add it to a touch screen experience in local. I am a newbie and what I did is to copy and paste the html page to Notepad++ and save it as hmtl page. For some reason the water effect doesn't show up and have an error message "TypeError: $(...).ripples is not a function".
Please let me know where I am failing or exact workflow to activate it locally. Thx!

**Comment by sirxemic** [comment]
Not an issue with the plugin itself, so I'm closing this.
