### ISSUE TITLE
Android with Chrome

### ISSUE THREAD

**Issue by alexfigliolia** [sirxemic/jquery.ripples#57]
Hey bud, big fan of your work. This has been one of my favorite gl effects for years now. I ran into an issue last week where an android device (running chrome) crashed when it couldn't support rendering to floating point textures. 

I know this something you've addressed in the past and after reading the code it's tough to tell where things went awry. All the necessary feature checks are present in the code (very well documented btw). 

When the website loads on the device it renders a blank screen with no ability to interact with content. The console error message is "Error: Rendering to floating point textures are not supported". This is the first time I've seen this error in a fatal instance. After some digging it appears that the browser passed all the necessary feature checks only to crash afterwards due to lack of support.

As you know, there are no issues on iOS running chrome or other browsers. Having used this plugin a few times in the past it was strange to notice this for the first time. Thanks for the great library and any help in advance. Cheers!

**Comment by sirxemic** [comment]
I saw your PR and this issue. Can you tell me if putting the initialization in a try-catch block fixes it as well?

**Comment by alexfigliolia** [comment]
It does. Totally slipped my mind. Thank you for the tip
