### ISSUE TITLE
Destroy and then re-init / pause trigger

### ISSUE THREAD

**Issue by alexeymakarov90** [sirxemic/jquery.ripples#6]
It would be great if after calling $(el).ripples('destroy') and then reiniting $(el).ripples({options...}) it would work :). Is there a pause trigger?

**Comment by alexeymakarov90** [comment]
The 'destroy' function has an error:
this.$el.removeClass('jquery-ripples').data('ripples', undefined); - this does not work with data!
Correct is:
this.$el.removeClass('jquery-ripples').removeData('ripples');

How to pause it ?

**Comment by sirxemic** [comment]
Thanks for your feedback! Fixed the destroy bug and implemented pause/play functionality.
