### ISSUE TITLE
Different background-image sources (url) changes the effect

### ISSUE THREAD

**Issue by Semipro211** [sirxemic/jquery.ripples#60]
So, I came upon an interesting issue when playing with this effect. When I use `background-image: url(https://images....);` the effect is beautiful and I have been able to experiment quite well with it. However, if I save that same background image locally with the repository (same size, file-type, pixels, etc.) and use, for example, `background-image: url('samephoto');` the effects become hardly noticeable. I have tried adjusting the parameter values and it still doesn't change much. Any idea what might be the issue?

**Comment by nitish29391** [comment]
You need to host that image on some port and access it through network same in the form of "http://localhost:80/abc/xyz.png".
Because the js which generates the ripple effect on image, that cannot read local file.
