### ISSUE TITLE
Destroy not stopping the rendering or removing the WebGL context 

### ISSUE THREAD

**Issue by GorelovNA** [sirxemic/jquery.ripples#63]
@sirxemic Hi, I have a completely identical problem like on this issue (https://github.com/sirxemic/jquery.ripples/issues/37) - destroy method does not destroy the WebGL context behind itself. I use the latest version of the library. Can you fix it please? The library is awesome!

P.S. In the screenshot, manually initialize and destroy the element cyclically. It can be seen that after the some operation the browser throws a warning
<img width="620" alt="ripples console screenshot" src="https://user-images.githubusercontent.com/40253335/64588706-e2d52a80-d3ab-11e9-9579-472eaefc02c7.png">

**Comment by sirxemic** [comment]
Thanks for the report. Should be fixed now!

**Comment by GorelovNA** [comment]
> Thanks for the report. Should be fixed now!

Thanks! Now it's great!
