### ISSUE TITLE
IPhone and IPad Issue

### ISSUE THREAD

**Issue by nirmalrepo** [sirxemic/jquery.ripples#66]
Hi,

Firstly, love your plugin.

I see the ripple effect is pixelated on iPhone and iPad and not smooth. 
![17975](https://user-images.githubusercontent.com/15866180/84838274-15742800-b08e-11ea-889f-6098f57f7240.jpg)

**Comment by BeZimar** [comment]
Having a mobile device issue as well, but in my case the background and the effect are both missing.

**Comment by sirxemic** [comment]
You'll have to give me a bit more details. It looks fine on the iPhones and iPads I tested it on. Are you having the same issues when you visit https://sirxemic.github.io/jquery.ripples/ on your devices?

**Comment by tjpicasso** [comment]
I fixed the issue by reducing the perturbance value
