### ISSUE TITLE
Effect not Working on Mobile Devices

### ISSUE THREAD

**Issue by BeZimar** [sirxemic/jquery.ripples#67]
Hello,

Thank you for this wonderful plugin and I have used it on a website powered by Webflow. It turned out beautifully. However, It somehow didn't work on mobile devices. Have Tried different browser/devices.

Here is the link: 
https://zimar.webflow.io/

Any ideas on the fix? Thank you!

**Comment by sirxemic** [comment]
Looks like the image is way too big for mobile. Try reducing it such that the biggest side is no more than 2048px.

**Comment by BeZimar** [comment]
> Looks like the image is way too big for mobile. Try reducing it such that the biggest side is no more than 2048px.

It worked...
Many thanks!!!!!
