### ISSUE TITLE
New coder here! Need Help

### ISSUE THREAD

**Issue by shreyaspaul** [sirxemic/jquery.ripples#68]
Hey OP.
Loved your plugin and I'd like to integrate it into my future projects too!

The problem I'm facing is: I can't seem to get the plugin running on a very simple html page.

Here is what I've done to my code:
1. Added Jquery via google cdn.
2. added a bg image to the body.
3. Added the code linking to the js file.
4. tried to initialize the plugin using the code you've mentioned.

The effect just does not come into effect.

It'd be great if you could help me learn this!

I'm adding my html file too.

[index.txt](https://github.com/sirxemic/jquery.ripples/files/4988277/index.txt)

**Comment by sirxemic** [comment]
I'm sure you've figured it out by now, but you were missing some initialization code:
```js
$('body').ripples({
	resolution: 512,
	dropRadius: 20,
	perturbance: 0.04,
});
```
