### ISSUE TITLE
open index.html fail

### ISSUE THREAD

**Issue by ArvoGuo** [sirxemic/jquery.ripples#7]
when I just open index.html,the error is:

Image from origin 'file://' has been blocked from loading by Cross-Origin Resource Sharing policy: Received an invalid response. Origin 'null' is therefore not allowed access.

when I run it with a server ,it's ok. I want to know why?

**Comment by sirxemic** [comment]
Does this answer your question? https://github.com/sirxemic/jquery.ripples/issues/1#issuecomment-38381566

**Comment by ArvoGuo** [comment]
get it. thx!
