### ISSUE TITLE
Ripples does not work on Samsung phones

### ISSUE THREAD

**Issue by tjpicasso** [sirxemic/jquery.ripples#70]
Hi I found out that the ripples does not work on Samsung devices.

Attached a screenshot

![Screenshot_20200825-164447_Chrome](https://user-images.githubusercontent.com/46502280/91124132-a866b980-e6f2-11ea-9667-dde0327b64a2.jpg)

**Comment by sirxemic** [comment]
It works on the Samsung phones I tested it on. But some smartphones don't support the WebGL features this plugin requires. Nothing can be done about that.
