### ISSUE TITLE
Effect not working on wordpress PLEASE Help

### ISSUE THREAD

**Issue by KimberKoding** [sirxemic/jquery.ripples#73]
Hi Team, 

I'm looking to get a cool looking effect added to my WordPress site, i'm using elementor to design the site and am having a hard time adding it.

I'm not sure if it's the Jquery version please help

**Comment by sirxemic** [comment]
Sounds like you need help on Wordpress and/or Elementor and not specifically this plugin. Therefore I'm closing this. If you can show some evidence there is something wrong with the plugin specifically that is preventing you from adding it to your website I'll open it again.
