### ISSUE TITLE
dropAtMouse mouse position bug

### ISSUE THREAD

**Issue by alexeymakarov90** [sirxemic/jquery.ripples#8]
Example:
```html
<div class="rippleWtihBg">
   <div class="divWithContent">
   </div>
</div>
```

After adding a canvas it does not read mouseover\mouseclick over .divWithContent - ripples show up on an left top corner +- 20px;

Fixed by changing in dropAtMouse function:
```javascript
e.offsetX || (e.pageX - this.$el.offset().left),
e.offsetY || (e.pageY - this.$el.offset().top),
```
to:
```javascript
(e.pageX - this.$el.offset().left) || e.offsetX,
(e.pageY - this.$el.offset().top) || e.offsetY,
```
Tested on Chrome\Mozilla.

**Comment by sirxemic** [comment]
Your comment was broken, so I fixed it.

I will take a look at this when I'm at home.
