### ISSUE TITLE
Document the format of the resolution property

### ISSUE THREAD

**Issue by rulatir** [sirxemic/jquery.ripples#80]
Is it an array of numbers representing width and height? An object with `width` and `height` properties? A string like `"1024x768"`? What exactly does it mean if only one size is specified (since the default is said to be simply `256`)?

**Comment by rulatir** [comment]
Misunderstood the description in the table, apparently it's just an integer and the texture is always square. But must it be a power of 2, or can it have any size?

**Comment by sirxemic** [comment]
That's a good point, it can be anything, but to make it work on most devices, it should be a power of 2 and not bigger than 2048.
