### ISSUE TITLE
Internet Explorer Issue

### ISSUE THREAD

**Issue by alluregraphicdesign** [sirxemic/jquery.ripples#9]
Hi, I'm using your jquery ripples effect on a pool service website here:  www.holidaypoolservice.ca and am currently having problems in Internet Explorer 11.

I’ve tried the website on all of our computers at work and my computer at home (all of which have auto-updates for IE) and the animation goes blank to a white colour after a quick flash. I’ve checked and it seems like everything is updated and installed (javascript, etc.).

Please advise if this is a bug and what can be done.  Thanks.

**Comment by sirxemic** [comment]
I'd say it is a bug. I think I'll try fix it when I've got the time.

I don't know if it actually works, but I think that changing the background-image URL to an absolute path fixes it for now in your case (so instead of using `url("img/pool.jpg")`, use `url("/wp-content/themes/holidaypool/img/pool.jpg")`).

**Comment by alluregraphicdesign** [comment]
Thanks, Pim.  I will let you know if this works.

*Alicia Hylton*
Allure Graphic Design

*Website*: www.alluregraphicdesign.com <http://www.alluregraphicdesign.com>
*Facebook*: Visit Us on Facebook 
<https://www.facebook.com/alluregraphicdesign>

**Comment by alluregraphicdesign** [comment]
Still doing the exact same thing. Unfortunately, it didn't help.  Can 
you let me know when you fix this?  Client is not happy about the way it 
looks in Internet Explorer.

Thanks,

*Alicia Hylton*
Allure Graphic Design

*Website*: www.alluregraphicdesign.com <http://www.alluregraphicdesign.com>
*Facebook*: Visit Us on Facebook 
<https://www.facebook.com/alluregraphicdesign>

**Comment by sirxemic** [comment]
Not sure if you were automatically notified when I closed this, but yeah, I think I fixed it.

**Comment by alluregraphicdesign** [comment]
Oh thanks, Pim.  Do I need to reinstall it on the website again?

*Alicia Hylton*
Allure Graphic Design

*Website*: www.alluregraphicdesign.com <http://www.alluregraphicdesign.com>
*Facebook*: Visit Us on Facebook 
<https://www.facebook.com/alluregraphicdesign>

**Comment by sirxemic** [comment]
Just replace your old code with the new, yes - https://github.com/sirxemic/jquery.ripples/blob/master/js/jquery.ripples.js

**Comment by alluregraphicdesign** [comment]
Thanks, Pim.  Everything is working now in all browsers!

*Alicia Hylton*
Allure Graphic Design

*Website*: www.alluregraphicdesign.com <http://www.alluregraphicdesign.com>
*Facebook*: Visit Us on Facebook 
<https://www.facebook.com/alluregraphicdesign>
